### ISSUE TITLE
Range for secondary detection frame

### ISSUE THREAD

**Issue by susanhc** [USTClj/Traffic_Sign_Recognition_Efficient_CNNs#5]
How do you determine the scope of the detection frame obtained by the detector for subsequent secondary detection?

**Comment by USTClj** [comment]
Hi, sorry for the late reply. The detection frame is obtained by average the run time of predicting the test images one by one.

**Comment by susanhc** [comment]
thanks for you reply!but I still dont't understand your meaning.when we abtain a detection bounding box by the base model like faster rcnn.Then you say there exist some not accuary deyection.So enlarge the bounding box scope for subsequent secondary detection.How did you make sure the scope?

**Comment by USTClj** [comment]
Hi, sorry for your confusion. My English is not good such that I misunderstand your issue. We enlarge the bounding box 2 times and then we refine the location via classical techniques. This step is not time consuming because the search area is not big. But it is not robust enough in some situations. You can develop our simple approach or a supervision approach which is in the Reference Section:

> Zhu, Zhe, et al. "An optimization approach for localization refinement of candidate traffic signs." IEEE Transactions on Intelligent Transportation Systems (2017).

Or you can try a feature pyramid network (FPN, such as the Mask R-CNN model) to regress the location of traffic signs. We have found that this manner is more effective and simple. Finally, we found that one main reason for the inaccurate regression is that we use the stride of the backbone too big and the training samples of small objects are not abundant. 

I hope I can help you and give you a proper answer this time!

**Comment by susanhc** [comment]
thanks your detailed reply!I will refer the paper you recommend to me and follow you advices.
